apiVersion: v1
kind: Pod
metadata:
  annotations:
    apps.tanzu.vmware.com/debug: "true"
    apps.tanzu.vmware.com/live-update: "true"
    autoscaling.knative.dev/maxScale: "1"
    autoscaling.knative.dev/minScale: "1"
    boot.spring.io/actuator: http://:8081/actuator
    boot.spring.io/version: 2.5.13
    conventions.apps.tanzu.vmware.com/applied-conventions: |-
      developer-conventions/debug-convention
      developer-conventions/live-update-convention
      developer-conventions/add-source-image-label
      spring-boot-convention/spring-boot
      spring-boot-convention/spring-boot-graceful-shutdown
      spring-boot-convention/spring-boot-web
      spring-boot-convention/spring-boot-actuator
      appliveview-sample/app-live-view-connector
      appliveview-sample/app-live-view-appflavours
      appliveview-sample/app-live-view-systemproperties
    developer.apps.tanzu.vmware.com/image-source-digest: 253bbd18ea1dbcd00efed35025118e5f4c321eca
    developer.conventions/target-containers: workload
    kubernetes.io/psp: privileged
    serving.knative.dev/creator: system:serviceaccount:default:default
  creationTimestamp: "2022-06-23T20:44:12Z"
  generateName: tanzu-java-web-app-00004-deployment-8485dc9bcd-
  labels:
    app: tanzu-java-web-app-00004
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/workload-name: tanzu-java-web-app
    conventions.apps.tanzu.vmware.com/framework: spring-boot
    pod-template-hash: 8485dc9bcd
    serving.knative.dev/configuration: tanzu-java-web-app
    serving.knative.dev/configurationGeneration: "4"
    serving.knative.dev/configurationUID: 90870b72-f6b0-47ce-a235-79f3a086de16
    serving.knative.dev/revision: tanzu-java-web-app-00004
    serving.knative.dev/revisionUID: c56174a3-1558-432f-acc3-75f12a3a92fc
    serving.knative.dev/service: tanzu-java-web-app
    serving.knative.dev/serviceUID: 06061510-c65f-4ded-939c-6b296bb09504
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8081"
    tanzu.app.live.view.application.flavours: spring-boot
    tanzu.app.live.view.application.name: demo
  name: tanzu-java-web-app-00004-deployment-8485dc9bcd-jl644
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: tanzu-java-web-app-00004-deployment-8485dc9bcd
    uid: 7e12758f-2f19-4c52-96e5-958b2516e3c0
  resourceVersion: "517456641"
  uid: 89c0c94e-a92d-498f-85e4-f9de7bf66eb2
spec:
  containers:
  - env:
    - name: BPL_DEBUG_ENABLED
      value: "true"
    - name: BPL_DEBUG_PORT
      value: "9005"
    - name: JAVA_TOOL_OPTIONS
      value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always
        -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=*
        -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081"
        -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
    - name: PORT
      value: "8080"
    - name: K_REVISION
      value: tanzu-java-web-app-00004
    - name: K_CONFIGURATION
      value: tanzu-java-web-app
    - name: K_SERVICE
      value: tanzu-java-web-app
    image: leke213.azurecr.io/supplychain-output-images/tanzu-java-web-app-default@sha256:aaca087f438b53757e27586875ca80aa464580890b397ab6d7373c62fab9ac01
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        httpGet:
          path: /wait-for-drain
          port: 8022
          scheme: HTTP
    name: workload
    ports:
    - containerPort: 8080
      name: user-port
      protocol: TCP
    resources: {}
    securityContext:
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gd9b4
      readOnly: true
  - env:
    - name: SERVING_NAMESPACE
      value: default
    - name: SERVING_SERVICE
      value: tanzu-java-web-app
    - name: SERVING_CONFIGURATION
      value: tanzu-java-web-app
    - name: SERVING_REVISION
      value: tanzu-java-web-app-00004
    - name: QUEUE_SERVING_PORT
      value: "8012"
    - name: CONTAINER_CONCURRENCY
      value: "0"
    - name: REVISION_TIMEOUT_SECONDS
      value: "300"
    - name: SERVING_POD
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: SERVING_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVING_LOGGING_CONFIG
    - name: SERVING_LOGGING_LEVEL
    - name: SERVING_REQUEST_LOG_TEMPLATE
      value: '{"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl":
        "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}",
        "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent":
        "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp":
        "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s",
        "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}'
    - name: SERVING_ENABLE_REQUEST_LOG
      value: "false"
    - name: SERVING_REQUEST_METRICS_BACKEND
      value: prometheus
    - name: TRACING_CONFIG_BACKEND
      value: none
    - name: TRACING_CONFIG_ZIPKIN_ENDPOINT
    - name: TRACING_CONFIG_DEBUG
      value: "false"
    - name: TRACING_CONFIG_SAMPLE_RATE
      value: "0.1"
    - name: USER_PORT
      value: "8080"
    - name: SYSTEM_NAMESPACE
      value: knative-serving
    - name: METRICS_DOMAIN
      value: knative.dev/internal/serving
    - name: SERVING_READINESS_PROBE
      value: '{"tcpSocket":{"port":8080,"host":"127.0.0.1"},"successThreshold":1}'
    - name: ENABLE_PROFILING
      value: "false"
    - name: SERVING_ENABLE_PROBE_REQUEST_LOG
      value: "false"
    - name: METRICS_COLLECTOR_ADDRESS
    - name: CONCURRENCY_STATE_ENDPOINT
    - name: CONCURRENCY_STATE_TOKEN_PATH
      value: /var/run/secrets/tokens/state-token
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: ENABLE_HTTP2_AUTO_DETECTION
      value: "false"
    image: leke213.azurecr.io/tanzu-application-platform/tap-packages@sha256:afcfb8360ba0b196f941e75fd660d83827f62a546729b7344d6226d1279708cf
    imagePullPolicy: IfNotPresent
    name: queue-proxy
    ports:
    - containerPort: 8022
      name: http-queueadm
      protocol: TCP
    - containerPort: 9090
      name: http-autometric
      protocol: TCP
    - containerPort: 9091
      name: http-usermetric
      protocol: TCP
    - containerPort: 8012
      name: queue-port
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        httpHeaders:
        - name: K-Network-Probe
          value: queue
        path: /
        port: 8012
        scheme: HTTP
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 25m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gd9b4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  imagePullSecrets:
  - name: registry-credentials
  - name: tap-registry
  - name: tbs-builder-secret-gen-placeholder-secret
  nodeName: aks-nodepool2-77904663-vmss000002
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 300
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-gd9b4
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-06-23T20:44:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-06-23T20:47:29Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-06-23T20:47:29Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-06-23T20:44:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://0f59a8c0d0b2cffd3a5a1d05af9c68ff0ea0ce9336d455b0584131bbadde686b
    image: sha256:7caf08e961395b947813a6ad207c9dc0570a44076eb1c87dcfbe652314578a52
    imageID: leke213.azurecr.io/tanzu-application-platform/tap-packages@sha256:afcfb8360ba0b196f941e75fd660d83827f62a546729b7344d6226d1279708cf
    lastState: {}
    name: queue-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-06-23T20:44:14Z"
  - containerID: containerd://dc1a4fc6a72342dc389533371933b591f7956402bee2338834a4650f612e5a6e
    image: sha256:113d8dd2c834cff801e2ab049ebdfea4d28382cb1d490f539d476cbfcf374956
    imageID: leke213.azurecr.io/supplychain-output-images/tanzu-java-web-app-default@sha256:aaca087f438b53757e27586875ca80aa464580890b397ab6d7373c62fab9ac01
    lastState: {}
    name: workload
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-06-23T20:44:14Z"
  hostIP: 10.240.0.8
  phase: Running
  podIP: 10.244.5.45
  podIPs:
  - ip: 10.244.5.45
  qosClass: Burstable
  startTime: "2022-06-23T20:44:13Z"
